version: 'Build #{build}'
image: Visual Studio 2022
configuration: Release
install:
  - ps: |
      Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
      & "$env:temp\dotnet-install.ps1" -Version 8.0.100-preview.7.23364.32
      dotnet new nugetconfig
      dotnet nuget add source -n dotnet8 https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet8/nuget/v3/index.json
before_build:
- dotnet restore
- dotnet restore -r win-x64
build_script:
- dotnet build
test_script:
- vstest.console /logger:Appveyor ClrDebug.Tests\bin\%CONFIGURATION%\net461\ClrDebug.Tests.dll /platform:x86 /InIsolation /TestCaseFilter:TestCategory!=SkipCI
- vstest.console /logger:Appveyor ClrDebug.Tests\bin\%CONFIGURATION%\net461\ClrDebug.Tests.dll /platform:x64 /InIsolation /TestCaseFilter:TestCategory!=SkipCI
#- vstest.console /logger:Appveyor ClrDebug.Tests\bin\%CONFIGURATION%\net8.0\ClrDebug.Tests.dll /platform:x86 /InIsolation /TestCaseFilter:TestCategory!=SkipCI
#- vstest.console /logger:Appveyor ClrDebug.Tests\bin\%CONFIGURATION%\net8.0\ClrDebug.Tests.dll /platform:x64 /InIsolation /TestCaseFilter:TestCategory!=SkipCI
after_test:
- dotnet pack ClrDebug\ClrDebug.csproj
- 7z a ClrDebug.zip .\ClrDebug\bin\%CONFIGURATION%\* -xr!*.json
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
artifacts:
  - path: '**/*.nupkg'
  - path: ClrDebug.zip
skip_commits:
  files:
    - '**/*.md'
    - '**/*.yml'
    - '**/*.png'
skip_tags: true
